[package]
name = "review-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20", features = ["full"] }
serde = { version = "1.0.100", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
axum = "0.6"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }
